<?php
/**
 * Страница "Форма настроек маршрутизации".
 * 
 * Русская локализации.
 * 
 * Этот файл является частью расширения модуля веб-приложения GearMagic.
 * 
 * @copyright Copyright (c) 2015 Веб-студия GearMagic
 * @license https://gearmagic.ru/license/
 */
?>
<article>
    <h1>Форма настроек маршрутизации</h1>
    <p>Форму настроек маршрутизации можно вызвать из:</p>
    <ul>
        <li>панели конфигурации веб-приложения;</li>
        <li>панели разделов "Конфигурация / Система";</li>
        <li>пуск, пункт "Конфигурация".</li>
    </ul>
    <h2>Поля формы</h2>
    <ul class="g-help-list">
        <li><b>Сбросить настройки.</b> Сбрасывает все настройки до значений по умолчанию (только после нажатия кнопки "Сохранить").</li>
    </ul>

    <h3>Общие правила формирования URL-адреса</h3>
    <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua и 
имеет следующие поля:</p>    
    <ul class="g-help-list">
        <li><b>ЧПУ для получения красивых URL-адресов.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat;</li>
        <li><b>Cлеш в конце URL-адреса.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat;</li>
        <li><b>Имя скрипта (index.php) в URL-адрес.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat;</li>
        <li><b>Параметр запроса URL-адреса.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat.</li>
    </ul>

    <h3>Правила формирования постоянных ссылок категорий и статей</h3>
    <p>Для формирования ссылок на страницах сайта применяются правила:</p>
    <ul class="g-help-list">
        <li><b>Простые.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat;</li>
        <li><b>Дата (месяц) с названием статьи.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat;</li>
        <li><b>Дата с названием статьи.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat;</li>
        <li><b>Идентификатор статьи с указателем.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat;</li>
        <li><b>азвание статьи с указателем.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat;</li>
        <li><b>Название статьи (.html) с указателем.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat;</li>
        <li><b>Название категории и статьи.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat;</li>
        <li><b>Название категории и статьи (.html).</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat;</li>
        <li><b>Название статьи (.html).</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat.</li>
    </ul>
</article>