<?php
/**
 * Страница "Форма настроек маршрутизации".
 * 
 * Английская (британская) локализация.
 * 
 * Этот файл является частью расширения модуля веб-приложения GearMagic.
 * 
 * @copyright Copyright (c) 2015 Веб-студия GearMagic
 * @license https://gearmagic.ru/license/
 */
?>
<article>
    <h1>Routing settings form</h1>
    <p>The routing settings form can be called from:</p>
    <ul>
        <li>web application configuration panel;</li>
        <li>partition bar "Configuration / System";</li>
        <li>start, item "Configuration".</li>
    </ul>
    <h2>Form fields</h2>
    <ul class="g-help-list">
        <li><b>Reset settings.</b> Resets all settings to default values (only after pressing the "Save" button).</li>
    </ul>

    <h3>General rules for generating a URL</h3>
    <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua and has the following fields:</p>    
    <ul class="g-help-list">
        <li><b>Friendly URL to get pretty URLs.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat;</li>
        <li><b>Slash at the end of the URL.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat;</li>
        <li><b>Script name (index.php) to URL.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat;</li>
        <li><b>URL query parameter.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat.</li>
    </ul>

    <h3>Rules for generating permalinks for categories and articles</h3>
    <p>Rules are applied to the formation of links on the pages of the site:</p>
    <ul class="g-help-list">
        <li><b>Simple.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat;</li>
        <li><b>Date (month) with article title.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat;</li>
        <li><b>Date with article title.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat;</li>
        <li><b>Article ID with pointer.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat;</li>
        <li><b>Article title with pointer.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat;</li>
        <li><b>Article title (.html) with pointer.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat;</li>
        <li><b>Category and article title.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat;</li>
        <li><b>Category and article title (.html).</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat;</li>
        <li><b>Article title (.html).</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat.</li>
    </ul>
</article>